# Generated by Django 4.2.2 on 2023-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera2',
            fields=[
                ('codigo2', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre2', models.CharField(max_length=50)),
                ('duracio2n', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
    ]
