# Generated by Django 4.2.2 on 2023-07-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0002_carrera2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrera2',
        ),
    ]
